services:
    data-warehouse:
        image: postgres:13
        env_file:
            - .env
        volumes:
            - "./postgres/data:/var/lib/postgresql/data:rw"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        ports:
            - "5432:5432"
        container_name: dwh

    pgadmin:
        image: dpage/pgadmin4
        env_file:
            - .env
        volumes:
            - "./data_pgadmin:/var/lib/pgadmin"
        ports:
            - "8080:80"

    etl-app:
        build: .
        env_file:
            - .env
        volumes:
            - "./scripts:/usr/app/scripts"
            - "./dataset:/usr/app/dataset"
            - "./postgres/dump:/usr/app/db_dump"
            - "./dbt/:/usr/app/dbt"
            - "./dbt_profile/:/root/.dbt/"
        depends_on:
            data-warehouse:
                condition: service_healthy
        container_name: etlapp